package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Baohanh generated by hbm2java
 */
@Entity
@Table(name = "baohanh", catalog = "qlchdd", uniqueConstraints = @UniqueConstraint(columnNames = "nhanvien_Tra"))
public class BaoHanh implements java.io.Serializable {

	private Integer maBh;
	private HoaDonBan hoadonban;
	private NhanVien nhanvienByNhanvienTra;
	private NhanVien nhanvienByNhanvienNhan;
	private SanPham sanpham;
	private Long serial;
	private String yeucauBh;
	private Date ngaynhan;
	private int tinhtrang;
	private Date ngaytra;

	public BaoHanh() {
	}

	public BaoHanh(HoaDonBan hoadonban, NhanVien nhanvienByNhanvienNhan, SanPham sanpham, Long serial, String yeucauBh,
			Date ngaynhan, int tinhtrang) {
		this.hoadonban = hoadonban;
		this.nhanvienByNhanvienNhan = nhanvienByNhanvienNhan;
		this.sanpham = sanpham;
		this.serial = serial;
		this.yeucauBh = yeucauBh;
		this.ngaynhan = ngaynhan;
		this.tinhtrang = tinhtrang;
	}

	public BaoHanh(HoaDonBan hoadonban, NhanVien nhanvienByNhanvienTra, NhanVien nhanvienByNhanvienNhan,
			SanPham sanpham, Long serial, String yeucauBh, Date ngaynhan, int tinhtrang, Date ngaytra) {
		this.hoadonban = hoadonban;
		this.nhanvienByNhanvienTra = nhanvienByNhanvienTra;
		this.nhanvienByNhanvienNhan = nhanvienByNhanvienNhan;
		this.sanpham = sanpham;
		this.serial = serial;
		this.yeucauBh = yeucauBh;
		this.ngaynhan = ngaynhan;
		this.tinhtrang = tinhtrang;
		this.ngaytra = ngaytra;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_BH", unique = true, nullable = false)
	public Integer getMaBh() {
		return this.maBh;
	}

	public void setMaBh(Integer maBh) {
		this.maBh = maBh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sohd_Ban", nullable = false)
	public HoaDonBan getHoadonban() {
		return this.hoadonban;
	}

	public void setHoadonban(HoaDonBan hoadonban) {
		this.hoadonban = hoadonban;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nhanvien_Tra", unique = true)
	public NhanVien getNhanvienByNhanvienTra() {
		return this.nhanvienByNhanvienTra;
	}

	public void setNhanvienByNhanvienTra(NhanVien nhanvienByNhanvienTra) {
		this.nhanvienByNhanvienTra = nhanvienByNhanvienTra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nhanvien_Nhan", nullable = false)
	public NhanVien getNhanvienByNhanvienNhan() {
		return this.nhanvienByNhanvienNhan;
	}

	public void setNhanvienByNhanvienNhan(NhanVien nhanvienByNhanvienNhan) {
		this.nhanvienByNhanvienNhan = nhanvienByNhanvienNhan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_SP", nullable = false)
	public SanPham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(SanPham sanpham) {
		this.sanpham = sanpham;
	}

	@Column(name = "serial", nullable = false)
	public Long getSerial() {
		return this.serial;
	}

	public void setSerial(Long serial) {
		this.serial = serial;
	}

	@Column(name = "yeucau_BH", nullable = false, length = 1000)
	public String getYeucauBh() {
		return this.yeucauBh;
	}

	public void setYeucauBh(String yeucauBh) {
		this.yeucauBh = yeucauBh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaynhan", nullable = false, length = 10)
	public Date getNgaynhan() {
		return this.ngaynhan;
	}

	public void setNgaynhan(Date ngaynhan) {
		this.ngaynhan = ngaynhan;
	}

	@Column(name = "tinhtrang", nullable = false)
	public int getTinhtrang() {
		return this.tinhtrang;
	}

	public void setTinhtrang(int tinhtrang) {
		this.tinhtrang = tinhtrang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaytra", length = 10)
	public Date getNgaytra() {
		return this.ngaytra;
	}

	public void setNgaytra(Date ngaytra) {
		this.ngaytra = ngaytra;
	}
}
