package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CthdMuaId generated by hbm2java
 */
@Embeddable
public class CthdMuaId implements java.io.Serializable {

	private int sohdMua;
	private int maSp;

	public CthdMuaId() {
	}

	public CthdMuaId(int sohdMua, int maSp) {
		this.sohdMua = sohdMua;
		this.maSp = maSp;
	}

	@Column(name = "sohd_Mua", nullable = false)
	public int getSohdMua() {
		return this.sohdMua;
	}

	public void setSohdMua(int sohdMua) {
		this.sohdMua = sohdMua;
	}

	@Column(name = "ma_SP", nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CthdMuaId))
			return false;
		CthdMuaId castOther = (CthdMuaId) other;

		return (this.getSohdMua() == castOther.getSohdMua()) && (this.getMaSp() == castOther.getMaSp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSohdMua();
		result = 37 * result + this.getMaSp();
		return result;
	}

}
