package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CthdBan generated by hbm2java
 */
@Entity
@Table(name = "cthd_ban", catalog = "qlchdd")
public class CthdBan implements java.io.Serializable {

	private CthdBanId id;
	private HoaDonBan hoadonban;
	private KhuyenMai khuyenmai;
	private SanPham sanpham;
	private Integer sl;
        private Double giaGoc;
        private Double tienGiam;
	private Double thanhtien;

	public CthdBan() {
	}

        public CthdBan(CthdBanId id, HoaDonBan hoadonban, KhuyenMai khuyenmai, SanPham sanpham, Integer sl, Double giaGoc, Double tienGiam) {
            this.id = id;
            this.hoadonban = hoadonban;
            this.khuyenmai = khuyenmai;
            this.sanpham = sanpham;
            this.sl = sl;
            this.giaGoc = giaGoc;
            this.tienGiam = tienGiam;
            this.thanhtien = 0.0D;
        }

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "sohdBan", column = @Column(name = "sohd_Ban", nullable = false)),
			@AttributeOverride(name = "maSp", column = @Column(name = "ma_SP", nullable = false)) })
	public CthdBanId getId() {
		return this.id;
	}

	public void setId(CthdBanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sohd_Ban", nullable = false, insertable = false, updatable = false)
	public HoaDonBan getHoadonban() {
		return this.hoadonban;
	}

	public void setHoadonban(HoaDonBan hoadonban) {
		this.hoadonban = hoadonban;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_KM", nullable = true)
	public KhuyenMai getKhuyenmai() {
		return this.khuyenmai;
	}

	public void setKhuyenmai(KhuyenMai khuyenmai) {
		this.khuyenmai = khuyenmai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_SP", nullable = false, insertable = false, updatable = false)
	public SanPham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(SanPham sanpham) {
		this.sanpham = sanpham;
	}

	@Column(name = "sl")
	public Integer getSl() {
		return this.sl;
	}

	public void setSl(Integer sl) {
		this.sl = sl;
	}

        @Column(name = "gia_Goc", precision = 22, scale = 0)
        public Double getGiaGoc() {
            return giaGoc;
        }

        public void setGiaGoc(Double giaGoc) {
            this.giaGoc = giaGoc;
        }

        @Column(name = "tien_Giam", precision = 22, scale = 0)
        public Double getTienGiam() {
            return tienGiam;
        }

        public void setTienGiam(Double tienGiam) {
            this.tienGiam = tienGiam;
        }
        
	@Column(name = "thanhtien", precision = 22, scale = 0, columnDefinition = "double default 0")
	public Double getThanhtien() {
		return this.thanhtien;
	}

	public void setThanhtien(Double thanhtien) {
		this.thanhtien = thanhtien;
	}

}
