package model.entities;
// Generated Dec 7, 2018 9:42:19 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CthdBanId generated by hbm2java
 */
@Embeddable
public class CthdBanId implements java.io.Serializable {

	private int sohdBan;
	private int maSp;

	public CthdBanId() {
	}

	public CthdBanId(int sohdBan, int maSp) {
		this.sohdBan = sohdBan;
		this.maSp = maSp;
	}

	@Column(name = "sohd_Ban", nullable = false)
	public int getSohdBan() {
		return this.sohdBan;
	}

	public void setSohdBan(int sohdBan) {
		this.sohdBan = sohdBan;
	}

	@Column(name = "ma_SP", nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CthdBanId))
			return false;
		CthdBanId castOther = (CthdBanId) other;

		return (this.getSohdBan() == castOther.getSohdBan()) && (this.getMaSp() == castOther.getMaSp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSohdBan();
		result = 37 * result + this.getMaSp();
		return result;
	}

}
