package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadonban generated by hbm2java
 */
@Entity
@Table(name = "hoadonban", catalog = "qlchdd")
public class HoaDonBan implements java.io.Serializable {

	private int sohdBan;
	private KhachHang khachhang;
	private NhanVien nhanvien;
	private Date ngayBan;
	private Double tongtienBan;
	private Set<CthdBan> cthdBans = new HashSet<CthdBan>(0);
	private Set<BaoHanh> baohanhs = new HashSet<BaoHanh>(0);

	public HoaDonBan() {
	}

	public HoaDonBan(KhachHang khachhang, NhanVien nhanvien, Date ngayBan) {
		this.khachhang = khachhang;
		this.nhanvien = nhanvien;
		this.ngayBan = ngayBan;
                this.tongtienBan = 0.0D;
	}
        
        public HoaDonBan(NhanVien nhanvien, Date ngayBan) {
		this.nhanvien = nhanvien;
		this.ngayBan = ngayBan;
                this.tongtienBan = 0.0D;
	}
        
        public HoaDonBan(int sohdBan, KhachHang khachhang, NhanVien nhanvien, Date ngayBan) {
                this.sohdBan = sohdBan;
		this.khachhang = khachhang;
		this.nhanvien = nhanvien;
		this.ngayBan = ngayBan;
                this.tongtienBan = 0.0D;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sohd_Ban", unique = true, nullable = false)
	public int getSohdBan() {
		return this.sohdBan;
	}

	public void setSohdBan(int sohdBan) {
		this.sohdBan = sohdBan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_KH")
	public KhachHang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(KhachHang khachhang) {
		this.khachhang = khachhang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_NV")
	public NhanVien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(NhanVien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay_Ban", length = 10)
	public Date getNgayBan() {
		return this.ngayBan;
	}

	public void setNgayBan(Date ngayBan) {
		this.ngayBan = ngayBan;
	}

	@Column(name = "tongtien_Ban", precision = 22, scale = 0, columnDefinition = "double default 0")
	public Double getTongtienBan() {
		return this.tongtienBan;
	}

	public void setTongtienBan(Double tongtienBan) {
		this.tongtienBan = tongtienBan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadonban", cascade = CascadeType.ALL)
	public Set<CthdBan> getCthdBans() {
		return this.cthdBans;
	}

	public void setCthdBans(Set<CthdBan> cthdBans) {
		this.cthdBans = cthdBans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadonban")
	public Set<BaoHanh> getBaohanhs() {
		return this.baohanhs;
	}

	public void setBaohanhs(Set<BaoHanh> baohanhs) {
		this.baohanhs = baohanhs;
	}

}
