package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadonmua generated by hbm2java
 */
@Entity
@Table(name = "hoadonmua", catalog = "qlchdd")
public class HoaDonMua implements java.io.Serializable {

	private Integer sohdMua;
	private NhaCungCap nhacungcap;
	private NhanVien nhanvien;
	private Date ngayNhap;
	private Double tongtienMua;
	private Set<CthdMua> cthdMuas = new HashSet<CthdMua>(0);

	public HoaDonMua() {
	}

	public HoaDonMua(NhanVien nhanvien) {
            this.nhanvien = nhanvien;
	}

	public HoaDonMua(NhaCungCap nhacungcap, NhanVien nhanvien, Date ngayNhap) {
            this.nhacungcap = nhacungcap;
            this.nhanvien = nhanvien;
            this.ngayNhap = ngayNhap;
            this.tongtienMua = 0.0d;
	}

        public HoaDonMua(Integer sohdMua, NhaCungCap nhacungcap, NhanVien nhanvien, Date ngayNhap) {
            this.sohdMua = sohdMua;
            this.nhacungcap = nhacungcap;
            this.nhanvien = nhanvien;
            this.ngayNhap = ngayNhap;
            this.tongtienMua = 0.0d;
        }
        
        
        
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sohd_Mua", unique = true, nullable = false)
	public Integer getSohdMua() {
		return this.sohdMua;
	}

	public void setSohdMua(Integer sohdMua) {
		this.sohdMua = sohdMua;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_NCC")
	public NhaCungCap getNhacungcap() {
		return this.nhacungcap;
	}

	public void setNhacungcap(NhaCungCap nhacungcap) {
		this.nhacungcap = nhacungcap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_NV", nullable = false)
	public NhanVien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(NhanVien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay_Nhap", length = 10)
	public Date getNgayNhap() {
		return this.ngayNhap;
	}

	public void setNgayNhap(Date ngayNhap) {
		this.ngayNhap = ngayNhap;
	}

	@Column(name = "tongtien_Mua", precision = 22, scale = 0, columnDefinition = "double default 0")
	public Double getTongtienMua() {
		return this.tongtienMua;
	}

	public void setTongtienMua(Double tongtienMua) {
		this.tongtienMua = tongtienMua;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadonmua", cascade = CascadeType.ALL)
	public Set<CthdMua> getCthdMuas() {
		return this.cthdMuas;
	}

	public void setCthdMuas(Set<CthdMua> cthdMuas) {
		this.cthdMuas = cthdMuas;
	}
}
