package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hoahong generated by hbm2java
 */
@Entity
@Table(name = "hoahong", catalog = "qlchdd")
public class HoaHong implements java.io.Serializable {

	private HoaHongId id;
	private NhanVien nhanvien;
	private Double tienHh;

	public HoaHong() {
	}

	public HoaHong(NhanVien nhanvien) {
		this.nhanvien = nhanvien;
                this.tienHh = 0.0D;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maNv", column = @Column(name = "ma_NV", nullable = false)),
			@AttributeOverride(name = "thang", column = @Column(name = "thang", nullable = false)),
			@AttributeOverride(name = "nam", column = @Column(name = "nam", nullable = false)) })
	public HoaHongId getId() {
		return this.id;
	}

	public void setId(HoaHongId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_NV", nullable = false, insertable = false, updatable = false)
	public NhanVien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(NhanVien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Column(name = "tien_HH", precision = 255, scale = 0)
	public Double getTienHh() {
		return this.tienHh;
	}

	public void setTienHh(Double tienHh) {
		this.tienHh = tienHh;
	}

}
