package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HoahongId generated by hbm2java
 */
@Embeddable
public class HoaHongId implements java.io.Serializable {

	private int maNv;
	private int thang;
	private int nam;

	public HoaHongId() {
	}

	public HoaHongId(int maNv, int thang, int nam) {
		this.maNv = maNv;
		this.thang = thang;
		this.nam = nam;
	}

	@Column(name = "ma_NV", nullable = false)
	public int getMaNv() {
		return this.maNv;
	}

	public void setMaNv(int maNv) {
		this.maNv = maNv;
	}

	@Column(name = "thang", nullable = false)
	public int getThang() {
		return this.thang;
	}

	public void setThang(int thang) {
		this.thang = thang;
	}

	@Column(name = "nam", nullable = false)
	public int getNam() {
		return this.nam;
	}

	public void setNam(int nam) {
		this.nam = nam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HoaHongId))
			return false;
		HoaHongId castOther = (HoaHongId) other;

		return (this.getMaNv() == castOther.getMaNv()) && (this.getThang() == castOther.getThang())
				&& (this.getNam() == castOther.getNam());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaNv();
		result = 37 * result + this.getThang();
		result = 37 * result + this.getNam();
		return result;
	}

}
