package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khachhang generated by hbm2java
 */
@Entity
@Table(name = "khachhang", catalog = "qlchdd")
public class KhachHang implements java.io.Serializable {

	private int maKh;
	private String tenKh;
	private Integer soCmndKh;
	private String diachiKh;
	private Integer soDtKh;
	private String email;
	private Set<HoaDonBan> hoadonbans = new HashSet<HoaDonBan>(0);

	public KhachHang() {
	}

	public KhachHang(int maKh, String tenKh, Integer soCmndKh, String diachiKh, Integer soDtKh, String email) {
		this.maKh = maKh;
		this.tenKh = tenKh;
		this.soCmndKh = soCmndKh;
		this.diachiKh = diachiKh;
		this.soDtKh = soDtKh;
		this.email = email;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_KH", unique = true, nullable = false)
	public int getMaKh() {
		return this.maKh;
	}

	public void setMaKh(int maKh) {
		this.maKh = maKh;
	}

	@Column(name = "ten_KH", length = 45)
	public String getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(String tenKh) {
		this.tenKh = tenKh;
	}

	@Column(name = "soCMND_KH")
	public Integer getSoCmndKh() {
		return this.soCmndKh;
	}

	public void setSoCmndKh(Integer soCmndKh) {
		this.soCmndKh = soCmndKh;
	}

	@Column(name = "diachi_KH", length = 45)
	public String getDiachiKh() {
		return this.diachiKh;
	}

	public void setDiachiKh(String diachiKh) {
		this.diachiKh = diachiKh;
	}

	@Column(name = "soDT_KH")
	public Integer getSoDtKh() {
		return this.soDtKh;
	}

	public void setSoDtKh(Integer soDtKh) {
		this.soDtKh = soDtKh;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khachhang")
	public Set<HoaDonBan> getHoadonbans() {
		return this.hoadonbans;
	}

	public void setHoadonbans(Set<HoaDonBan> hoadonbans) {
		this.hoadonbans = hoadonbans;
	}
        
}
