package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Khuyenmai generated by hbm2java
 */
@Entity
@Table(name = "khuyenmai", catalog = "qlchdd")
public class KhuyenMai implements java.io.Serializable {

	private int maKm;
	private String tenKm;
	private Float hsKm;
	private Date ngayBd;
	private Date ngayKt;
	private Set<CthdBan> cthdBans = new HashSet<CthdBan>(0);
	private Set<SanPham> sanphams = new HashSet<SanPham>(0);

	public KhuyenMai() {
	}

	public KhuyenMai(int maKm) {
		this.maKm = maKm;
	}

	public KhuyenMai(int maKm, String tenKm, Float hsKm, Date ngayBd, Date ngayKt) {
		this.maKm = maKm;
		this.tenKm = tenKm;
		this.hsKm = hsKm;
		this.ngayBd = ngayBd;
		this.ngayKt = ngayKt;
	}

	@Id

	@Column(name = "ma_KM", unique = true, nullable = false)
	public int getMaKm() {
		return this.maKm;
	}

	public void setMaKm(int maKm) {
		this.maKm = maKm;
	}

	@Column(name = "ten_KM", length = 45)
	public String getTenKm() {
		return this.tenKm;
	}

	public void setTenKm(String tenKm) {
		this.tenKm = tenKm;
	}

	@Column(name = "hs_KM", precision = 12, scale = 0)
	public Float getHsKm() {
		return this.hsKm;
	}

	public void setHsKm(Float hsKm) {
		this.hsKm = hsKm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay_BD", length = 10)
	public Date getNgayBd() {
		return this.ngayBd;
	}

	public void setNgayBd(Date ngayBd) {
		this.ngayBd = ngayBd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay_KT", length = 10)
	public Date getNgayKt() {
		return this.ngayKt;
	}

	public void setNgayKt(Date ngayKt) {
		this.ngayKt = ngayKt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khuyenmai")
	public Set<CthdBan> getCthdBans() {
		return this.cthdBans;
	}

	public void setCthdBans(Set<CthdBan> cthdBans) {
		this.cthdBans = cthdBans;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ctkm", catalog = "qlchdd", joinColumns = {
			@JoinColumn(name = "ma_KM", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ma_SP", nullable = false, updatable = false) })
	public Set<SanPham> getSanphams() {
		return this.sanphams;
	}

	public void setSanphams(Set<SanPham> sanphams) {
		this.sanphams = sanphams;
	}

}
