package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhacungcap generated by hbm2java
 */
@Entity
@Table(name = "nhacungcap", catalog = "qlchdd")
public class NhaCungCap implements java.io.Serializable {

	private int maNcc;
	private String tenNcc;
	private String diachiNcc;
	private Integer soDtNcc;
	private Integer tinhTrang;
	private Set<HoaDonMua> hoadonmuas = new HashSet<HoaDonMua>(0);

	public NhaCungCap() {
	}

	public NhaCungCap(String tenNcc, String diachiNcc, Integer soDtNcc, Integer tinhTrang) {
            this.tenNcc = tenNcc;
            this.diachiNcc = diachiNcc;
            this.soDtNcc = soDtNcc;
            this.tinhTrang = tinhTrang;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_NCC", unique = true, nullable = false)
	public int getMaNcc() {
		return this.maNcc;
	}

	public void setMaNcc(int maNcc) {
		this.maNcc = maNcc;
	}

	@Column(name = "ten_NCC", length = 45)
	public String getTenNcc() {
		return this.tenNcc;
	}

	public void setTenNcc(String tenNcc) {
		this.tenNcc = tenNcc;
	}

	@Column(name = "diachi_NCC", length = 45)
	public String getDiachiNcc() {
		return this.diachiNcc;
	}

	public void setDiachiNcc(String diachiNcc) {
		this.diachiNcc = diachiNcc;
	}

	@Column(name = "soDT_NCC")
	public Integer getSoDtNcc() {
		return this.soDtNcc;
	}

	public void setSoDtNcc(Integer soDtNcc) {
		this.soDtNcc = soDtNcc;
	}

	@Column(name = "tinh_trang")
	public Integer getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(Integer tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhacungcap")
	public Set<HoaDonMua> getHoadonmuas() {
		return this.hoadonmuas;
	}

	public void setHoadonmuas(Set<HoaDonMua> hoadonmuas) {
		this.hoadonmuas = hoadonmuas;
	}

}
