package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Nhasanxuat generated by hbm2java
 */
@Entity
@Table(name = "nhasanxuat", catalog = "qlchdd")
public class NhaSanXuat implements java.io.Serializable {

	private int maNsx;
	private String tenNsx;
	private String thongtin;
        private Set<SanPham> sanphams= new HashSet<SanPham>(0);

	public NhaSanXuat() {
	}

	public NhaSanXuat(String tenNsx, String thongtin) {
		this.tenNsx = tenNsx;
		this.thongtin = thongtin;
	}

        public NhaSanXuat(int maNsx, String tenNsx, String thongtin) {
            this.maNsx = maNsx;
            this.tenNsx = tenNsx;
            this.thongtin = thongtin;
        }

	@Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_nsx", unique = true, nullable = false)
	public int getMaNsx() {
		return this.maNsx;
	}

	public void setMaNsx(int maNsx) {
		this.maNsx = maNsx;
	}

	@Column(name = "ten_nsx", nullable = false, length = 45)
	public String getTenNsx() {
		return this.tenNsx;
	}

	public void setTenNsx(String tenNsx) {
		this.tenNsx = tenNsx;
	}

	@Column(name = "thongtin", nullable = false, length = 45)
	public String getThongtin() {
		return this.thongtin;
	}

	public void setThongtin(String thongtin) {
		this.thongtin = thongtin;
	}

        @OneToMany(fetch = FetchType.LAZY, mappedBy = "nhasanxuat")
	public Set<SanPham> getSanphams() {
            return sanphams;
        }

        public void setSanphams(Set<SanPham> sanphams) {
            this.sanphams = sanphams;
        }

    @Override
    public String toString() {
        return tenNsx;
    }
}
