package model.entities;
// Generated Dec 7, 2018 9:42:19 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Nhasanxuat generated by hbm2java
 */
@Entity
@Table(name = "nhasanxuat", catalog = "qlchdd")
public class NhaSanXuat implements java.io.Serializable {

	private int maNsx;
	private SanPham sanpham;
	private String tenNsx;
	private String thongtin;

	public NhaSanXuat() {
	}

	public NhaSanXuat(SanPham sanpham, String tenNsx, String thongtin) {
		this.sanpham = sanpham;
		this.tenNsx = tenNsx;
		this.thongtin = thongtin;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "sanpham"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ma_nsx", unique = true, nullable = false)
	public int getMaNsx() {
		return this.maNsx;
	}

	public void setMaNsx(int maNsx) {
		this.maNsx = maNsx;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public SanPham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(SanPham sanpham) {
		this.sanpham = sanpham;
	}

	@Column(name = "ten_nsx", nullable = false, length = 45)
	public String getTenNsx() {
		return this.tenNsx;
	}

	public void setTenNsx(String tenNsx) {
		this.tenNsx = tenNsx;
	}

	@Column(name = "thongtin", nullable = false, length = 45)
	public String getThongtin() {
		return this.thongtin;
	}

	public void setThongtin(String thongtin) {
		this.thongtin = thongtin;
	}

}
