package model.entities;
// Generated Dec 7, 2018 9:42:19 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sanpham generated by hbm2java
 */
@Entity
@Table(name = "sanpham", catalog = "qlchdd")
public class SanPham implements java.io.Serializable {

	private int maSp;
	private String tenSp;
	private String loai;
	private Integer maNsx;
	private Integer sl;
	private Date ngaySx;
	private Double thueVat;
	private Double giaBanRa;
	private Integer thoigianBh;
	private String xuatxu;
	private String mau;
	private String bonho;
	private String kichthuoc;
	private byte[] anh;
	private Set<KhuyenMai> khuyenmais = new HashSet<KhuyenMai>(0);
	private Set<CthdMua> cthdMuas = new HashSet<CthdMua>(0);
	private Set<CthdBan> cthdBans = new HashSet<CthdBan>(0);
	private NhaSanXuat nhasanxuat;

	public SanPham() {
	}

	public SanPham(int maSp) {
		this.maSp = maSp;
	}

	public SanPham(int maSp, String tenSp, String loai, Integer maNsx, Integer sl, Date ngaySx, Double thueVat,
			Double giaBanRa, Integer thoigianBh, String xuatxu, String mau, String bonho, String kichthuoc, byte[] anh,
			Set<KhuyenMai> khuyenmais, Set<CthdMua> cthdMuas, Set<CthdBan> cthdBans, NhaSanXuat nhasanxuat) {
		this.maSp = maSp;
		this.tenSp = tenSp;
		this.loai = loai;
		this.maNsx = maNsx;
		this.sl = sl;
		this.ngaySx = ngaySx;
		this.thueVat = thueVat;
		this.giaBanRa = giaBanRa;
		this.thoigianBh = thoigianBh;
		this.xuatxu = xuatxu;
		this.mau = mau;
		this.bonho = bonho;
		this.kichthuoc = kichthuoc;
		this.anh = anh;
		this.khuyenmais = khuyenmais;
		this.cthdMuas = cthdMuas;
		this.cthdBans = cthdBans;
		this.nhasanxuat = nhasanxuat;
	}

	@Id

	@Column(name = "ma_SP", unique = true, nullable = false)
	public int getMaSp() {
		return this.maSp;
	}

	public void setMaSp(int maSp) {
		this.maSp = maSp;
	}

	@Column(name = "ten_SP", length = 45)
	public String getTenSp() {
		return this.tenSp;
	}

	public void setTenSp(String tenSp) {
		this.tenSp = tenSp;
	}

	@Column(name = "loai", length = 45)
	public String getLoai() {
		return this.loai;
	}

	public void setLoai(String loai) {
		this.loai = loai;
	}

	@Column(name = "ma_nsx")
	public Integer getMaNsx() {
		return this.maNsx;
	}

	public void setMaNsx(Integer maNsx) {
		this.maNsx = maNsx;
	}

	@Column(name = "sl")
	public Integer getSl() {
		return this.sl;
	}

	public void setSl(Integer sl) {
		this.sl = sl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_SX", length = 19)
	public Date getNgaySx() {
		return this.ngaySx;
	}

	public void setNgaySx(Date ngaySx) {
		this.ngaySx = ngaySx;
	}

	@Column(name = "thue_VAT", precision = 22, scale = 0)
	public Double getThueVat() {
		return this.thueVat;
	}

	public void setThueVat(Double thueVat) {
		this.thueVat = thueVat;
	}

	@Column(name = "gia_BanRa", precision = 22, scale = 0)
	public Double getGiaBanRa() {
		return this.giaBanRa;
	}

	public void setGiaBanRa(Double giaBanRa) {
		this.giaBanRa = giaBanRa;
	}

	@Column(name = "thoigian_BH")
	public Integer getThoigianBh() {
		return this.thoigianBh;
	}

	public void setThoigianBh(Integer thoigianBh) {
		this.thoigianBh = thoigianBh;
	}

	@Column(name = "xuatxu", length = 45)
	public String getXuatxu() {
		return this.xuatxu;
	}

	public void setXuatxu(String xuatxu) {
		this.xuatxu = xuatxu;
	}

	@Column(name = "mau", length = 45)
	public String getMau() {
		return this.mau;
	}

	public void setMau(String mau) {
		this.mau = mau;
	}

	@Column(name = "bonho", length = 45)
	public String getBonho() {
		return this.bonho;
	}

	public void setBonho(String bonho) {
		this.bonho = bonho;
	}

	@Column(name = "kichthuoc", length = 45)
	public String getKichthuoc() {
		return this.kichthuoc;
	}

	public void setKichthuoc(String kichthuoc) {
		this.kichthuoc = kichthuoc;
	}

	@Column(name = "anh")
	public byte[] getAnh() {
		return this.anh;
	}

	public void setAnh(byte[] anh) {
		this.anh = anh;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "sanphams")
	public Set<KhuyenMai> getKhuyenmais() {
		return this.khuyenmais;
	}

	public void setKhuyenmais(Set<KhuyenMai> khuyenmais) {
		this.khuyenmais = khuyenmais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanpham")
	public Set<CthdMua> getCthdMuas() {
		return this.cthdMuas;
	}

	public void setCthdMuas(Set<CthdMua> cthdMuas) {
		this.cthdMuas = cthdMuas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanpham")
	public Set<CthdBan> getCthdBans() {
		return this.cthdBans;
	}

	public void setCthdBans(Set<CthdBan> cthdBans) {
		this.cthdBans = cthdBans;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "sanpham")
	public NhaSanXuat getNhasanxuat() {
		return this.nhasanxuat;
	}

	public void setNhasanxuat(NhaSanXuat nhasanxuat) {
		this.nhasanxuat = nhasanxuat;
	}

}
