package model.entities;
// Generated Dec 7, 2018 9:42:19 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "qlchdd")
public class TaiKhoan implements java.io.Serializable {

	private String tenDangNhap;
	private NhanVien nhanvien;
	private PhanQuyen phanquyen;
	private String matkhauDangNhap;

	public TaiKhoan() {
	}

	public TaiKhoan(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public TaiKhoan(String tenDangNhap, NhanVien nhanvien, PhanQuyen phanquyen, String matkhauDangNhap) {
		this.tenDangNhap = tenDangNhap;
		this.nhanvien = nhanvien;
		this.phanquyen = phanquyen;
		this.matkhauDangNhap = matkhauDangNhap;
	}

	@Id

	@Column(name = "ten_DangNhap", unique = true, nullable = false, length = 45)
	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_NV")
	public NhanVien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(NhanVien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_PhanQuyen")
	public PhanQuyen getPhanquyen() {
		return this.phanquyen;
	}

	public void setPhanquyen(PhanQuyen phanquyen) {
		this.phanquyen = phanquyen;
	}

	@Column(name = "matkhau_DangNhap", length = 45)
	public String getMatkhauDangNhap() {
		return this.matkhauDangNhap;
	}

	public void setMatkhauDangNhap(String matkhauDangNhap) {
		this.matkhauDangNhap = matkhauDangNhap;
	}

}
