package model.entities;
// Generated Dec 11, 2018 1:37:51 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Taikhoan generated by hbm2java
 */

@NamedNativeQueries({
    @NamedNativeQuery(
    name = "USP_Login",
    query = "CALL USP_Login(:tenDangNhap, :matKhau)",
    resultClass = TaiKhoan.class
    ),
    @NamedNativeQuery(
    name = "USP_ResetPasswordtAccount ",
    query = "CALL USP_ResetPasswordtAccount(:tenDangNhap)",
    resultClass = TaiKhoan.class
    )
})

@Entity
@Table(name = "taikhoan", catalog = "qlchdd")
public class TaiKhoan implements java.io.Serializable {

	private String tenDangNhap;
	private NhanVien nhanvien;
	private PhanQuyen phanquyen;
	private String matkhauDangNhap;

	public TaiKhoan() {
	}

	public TaiKhoan(String tenDangNhap, PhanQuyen phanquyen) {
		this.tenDangNhap = tenDangNhap;
		this.phanquyen = phanquyen;
	}

	@Id

	@Column(name = "ten_DangNhap", unique = true, nullable = false, length = 45)
	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_PhanQuyen", nullable = false)
	public PhanQuyen getPhanquyen() {
		return this.phanquyen;
	}

	public void setPhanquyen(PhanQuyen phanquyen) {
		this.phanquyen = phanquyen;
	}

	@Column(name = "matkhau_DangNhap", length = 45)
	public String getMatkhauDangNhap() {
		return this.matkhauDangNhap;
	}

	public void setMatkhauDangNhap(String matkhauDangNhap) {
		this.matkhauDangNhap = matkhauDangNhap;
	}

        @OneToOne
        @JoinColumn(name = "ma_NV", nullable = true)
	public NhanVien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(NhanVien nhanvien) {
		this.nhanvien = nhanvien;
	}
}
